import { createHash, randomUUID } from "node:crypto";
import type { StrategyPreview, StrategyReport } from "@/lib/strategy/schema";

const memoryCounts = new Map<string, { count: number; resetAt: number }>();
const memoryReports = new Map<string, { report: StrategyReport; expiresAt: number }>();
const memoryRequestIds = new Map<string, { reportId: string; expiresAt: number }>();
const REPORT_TTL = 7 * 86_400;
function redisConfigured() { return Boolean(process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN); }
async function redisCommand<T>(command: Array<string | number>) { const url = process.env.UPSTASH_REDIS_REST_URL; const token = process.env.UPSTASH_REDIS_REST_TOKEN; if (!url || !token) return null; const response = await fetch(url, { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(command), signal: AbortSignal.timeout(4_000) }); if (!response.ok) throw new Error("Redis request failed"); return ((await response.json()) as { result?: T }).result ?? null; }
function hash(value: string) { return createHash("sha256").update(`${process.env.SCAN_RATE_LIMIT_SALT ?? "frontiergtm-strategy-dev"}:${value}`).digest("hex"); }
function reportKey(id: string) { return `frontiergtm:strategy:report:v1:${id}`; }
export function strategyConfigured() { return process.env.NODE_ENV !== "production" || redisConfigured(); }
export function strategyCheckoutConfigured() { return Boolean(process.env.STRIPE_SECRET_KEY); }
export function strategyPriceCents() { const value = Number(process.env.STRATEGY_PRICE_CENTS || 14900); return Number.isInteger(value) && value >= 500 && value <= 500_000 ? value : 14900; }
export async function checkStrategyRate(identifier: string, limit = 3, scope = "brief") { const epoch = process.env.STRATEGY_RATE_LIMIT_EPOCH?.trim() || "v1"; const key = `frontiergtm:strategy:rate:${epoch}:${scope}:${hash(identifier)}`; if (redisConfigured()) { const count = Number((await redisCommand<number>(["INCR", key])) ?? 0); if (count === 1) await redisCommand(["EXPIRE", key, 86_400]); return { allowed: count <= limit, remaining: Math.max(limit - count, 0) }; } const now = Date.now(); const current = memoryCounts.get(key); const entry = !current || current.resetAt < now ? { count: 1, resetAt: now + 86_400_000 } : { ...current, count: current.count + 1 }; memoryCounts.set(key, entry); return { allowed: entry.count <= limit, remaining: Math.max(limit - entry.count, 0) }; }
export function strategyRequestKey(input: object) { return `frontiergtm:strategy:request:v1:${hash(JSON.stringify(input))}`; }
export async function getStrategyReport(id: string) { if (redisConfigured()) { const value = await redisCommand<string>(["GET", reportKey(id)]); if (!value) return null; try { return JSON.parse(value) as StrategyReport; } catch { return null; } } const stored = memoryReports.get(id); return stored && stored.expiresAt > Date.now() ? stored.report : null; }
export async function getStrategyReportId(key: string) { if (redisConfigured()) return redisCommand<string>(["GET", key]); const stored = memoryRequestIds.get(key); return stored && stored.expiresAt > Date.now() ? stored.reportId : null; }
export async function storeStrategyReport(key: string, report: StrategyReport) { const id = randomUUID(); if (redisConfigured()) await Promise.all([redisCommand(["SET", reportKey(id), JSON.stringify(report), "EX", REPORT_TTL]), redisCommand(["SET", key, id, "EX", REPORT_TTL])]); else { const expiresAt = Date.now() + REPORT_TTL * 1_000; memoryReports.set(id, { report, expiresAt }); memoryRequestIds.set(key, { reportId: id, expiresAt }); } return id; }
export function previewStrategy(reportId: string, report: StrategyReport): StrategyPreview { return { reportId, priceCents: strategyPriceCents(), identity: report.identity, verdict: report.verdict, preview: report.preview, executiveStrategy: report.executiveStrategy, evidenceCoverage: report.evidenceCoverage, sources: report.sources, generatedAt: report.generatedAt }; }
export async function storeStrategyPurchase(payload: Record<string, unknown>) { if (!redisConfigured()) return false; const value = JSON.stringify({ ...payload, source: "frontiergtm_strategy", recordedAt: new Date().toISOString() }); await redisCommand(["LPUSH", "frontiergtm:strategy:purchases:v1", value]); await redisCommand(["LTRIM", "frontiergtm:strategy:purchases:v1", 0, 4_999]); return true; }
