export const frontierSkills = [
  {
    name: "Scan",
    slug: "frontiergtm-scan",
    number: "01",
    question: "Where is the GTM story breaking?",
    description: "Diagnose positioning, buyer clarity, differentiation, proof, and the conversion path from public or supplied evidence.",
    outcome: "A scored diagnosis and three ranked GTM moves.",
    type: "Positioning",
    icon: "compass",
  },
  {
    name: "Signal",
    slug: "frontiergtm-signal",
    number: "02",
    question: "What changed—and what should we do?",
    description: "Research recent market and competitor changes, distinguish evidence from inference, and translate the strongest signals into action.",
    outcome: "A source-backed executive brief with 7–30 day actions.",
    type: "Market intelligence",
    icon: "nodes",
  },
  {
    name: "Launch",
    slug: "frontiergtm-launch",
    number: "03",
    question: "Is this launch ready to create movement?",
    description: "Pressure-test readiness and build the buyer frame, launch thesis, narrative, claim stack, activation system, and fourteen-day sequence.",
    outcome: "A launch verdict and coordinated operating plan.",
    type: "Launch strategy",
    icon: "rocket",
  },
  {
    name: "Account Brief",
    slug: "frontiergtm-account-brief",
    number: "04",
    question: "Why this account, why now?",
    description: "Combine public evidence with opportunity context to form an account thesis, buying-situation hypotheses, discovery plan, and relevant proof.",
    outcome: "A sales-ready executive account brief.",
    type: "Account strategy",
    icon: "target",
  },
  {
    name: "Agent Blueprint",
    slug: "frontiergtm-agent-blueprint",
    number: "05",
    question: "Should this GTM job become an agent?",
    description: "Choose the simplest adequate solution, then map the agent contract, tools, context, controls, evaluations, and thin-slice pilot.",
    outcome: "A build/no-build decision and governable system blueprint.",
    type: "GTM engineering",
    icon: "robot",
  },
] as const;

export const frontierSkillsRepository = "https://github.com/ryanpollock/frontiergtm-skills";
