import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { ZodError } from "zod";
import { strategyCheckoutSchema } from "@/lib/strategy/schema";
import { checkStrategyRate, getStrategyReport, strategyCheckoutConfigured, strategyPriceCents } from "@/lib/strategy/storage";

export const runtime = "nodejs";
function clientIdentifier(request: NextRequest) { return request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || request.headers.get("x-real-ip") || "unknown"; }
function origin(request: NextRequest) { const configured = process.env.NEXT_PUBLIC_SITE_URL?.trim(); if (configured) return configured.replace(/\/$/, ""); const value = request.nextUrl.origin; return value.startsWith("http://localhost") || value.startsWith("http://127.0.0.1") ? value : "https://www.frontiergtm.ai"; }
export async function POST(request: NextRequest) { try { if (!strategyCheckoutConfigured()) return NextResponse.json({ error: "checkout_unconfigured", message: "Paid Strategy Briefs are not open yet. Email Ryan for founding access." }, { status: 503 }); const payload = strategyCheckoutSchema.parse(await request.json()); if (payload.website) return NextResponse.json({ error: "invalid_request", message: "Invalid request." }, { status: 400 }); const rate = await checkStrategyRate(clientIdentifier(request), 8, "checkout"); if (!rate.allowed) return NextResponse.json({ error: "rate_limited", message: "Too many checkout attempts. Please try again later." }, { status: 429 }); const report = await getStrategyReport(payload.reportId); if (!report) return NextResponse.json({ error: "report_expired", message: "This strategy brief has expired. Generate a fresh preview to continue." }, { status: 404 }); const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!); const session = await stripe.checkout.sessions.create({ mode: "payment", allow_promotion_codes: true, customer_email: payload.email, client_reference_id: payload.reportId, metadata: { reportId: payload.reportId, product: "frontiergtm_strategy" }, payment_intent_data: { description: `FrontierGTM Strategy — ${report.identity.companyName}`, metadata: { reportId: payload.reportId, product: "frontiergtm_strategy" } }, line_items: [{ quantity: 1, price_data: { currency: "usd", unit_amount: strategyPriceCents(), product_data: { name: "FrontierGTM Strategy Brief", description: `Complete 90-day GTM Strategy Brief for ${report.identity.companyName}` } } }], success_url: `${origin(request)}/strategy?report=${encodeURIComponent(payload.reportId)}&session_id={CHECKOUT_SESSION_ID}`, cancel_url: `${origin(request)}/strategy?report=${encodeURIComponent(payload.reportId)}&checkout=cancelled` }); if (!session.url) throw new Error("Stripe returned no URL"); return NextResponse.json({ url: session.url }); } catch (error) { if (error instanceof ZodError) return NextResponse.json({ error: "invalid_request", message: "Enter a valid work email and try again." }, { status: 400 }); if (error instanceof Stripe.errors.StripeError) console.error("Strategy checkout failed", { type: error.type, code: error.code, message: error.message }); return NextResponse.json({ error: "checkout_failed", message: "Checkout could not start just now. Please try again." }, { status: 500 }); } }
